# Early exit for non-interactive shells
case $- in
    *i*) ;;
      *) return;;
esac

# Common shell configs
if [ -f $HOME/.common_env ]; then
    source $HOME/.common_env
fi

# Surface size updates
shopt -s checkwinsize
