#!/usr/bin/env python3

import os
import sys

PATH = "/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"

try:
    if (os.geteuid() != 0):
        raise Exception("Root privileges required")

    if(len(sys.argv) < 2):
        raise Exception("Incomplete arguments")

    match sys.argv[1]:
        case "status":
            Conf = open(PATH, "r")
            print("enabled" if Conf.read() == "1\n" else "disabled")

        case "enable":
            Conf = open(PATH, "w")
            Conf.write("1")
            print("Battery care enabled.")

        case "disable":
            Conf = open(PATH, "w")
            Conf.write("0")
            print("Battery care disabled.")

        case _:
            print("Invalid operation.")

except Exception as Except:
    print(str(Except))